name: Release Please

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  weekly-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set week tag
        id: week
        run: |
          YEAR=$(date +'%Y')
          WEEK=$(date +'%V') # ISO 주차 (01~53)
          TAG="v${YEAR}-w${WEEK}"
          echo "tag=$TAG" >> $GITHUB_OUTPUT

      - name: Create Git Tag (if not exists)
        run: |
          git fetch --tags
          if git rev-parse "${{ steps.week.outputs.tag }}" >/dev/null 2>&1; then
            echo "Tag ${{ steps.week.outputs.tag }} already exists. Skipping tag creation."
          else
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git tag ${{ steps.week.outputs.tag }}
            git push origin ${{ steps.week.outputs.tag }}
          fi

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install conventional-changelog
        run: npm install -g conventional-changelog-cli

      - name: Generate Changelog
        run: |
          npx conventional-changelog -p angular -i CHANGELOG.md -s -r 0

      - name: Commit Changelog
        run: |
          git add CHANGELOG.md
          git commit -m "docs(changelog): update for ${{ steps.week.outputs.tag }}" || echo "No changes"
          git push origin main
